# Generated by Django 4.2.16 on 2024-11-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recent_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentproduct',
            options={'ordering': ['-date_added']},
        ),
    ]
