# Generated by Django 4.2.16 on 2024-09-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_featuredbrand_featuredcategory_featuredproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedBrand',
        ),
        migrations.DeleteModel(
            name='FeaturedCategory',
        ),
        migrations.DeleteModel(
            name='FeaturedProduct',
        ),
    ]
