# Generated by Django 4.2.16 on 2024-09-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_color_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
