# Generated by Django 4.2.16 on 2024-09-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
