# Generated by Django 4.2.16 on 2024-10-15 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnage', models.CharField(choices=[('LPG', 'LPG'), ('8-10 tonnes', '8 to 10 Tonnes'), ('10-12 tonnes', '10 to 12 Tonnes'), ('13-15 tonnes', '13 to 15 Tonnes'), ('16-20 tonnes', '16 to 20 Tonnes'), ('21-25 tonnes', '21 to 25 Tonnes'), ('petrol-diesel', 'Petrol and Diesel'), ('9000 litres', '9,000 Litres'), ('10000 litres', '10,000 Litres'), ('13500 litres', '13,500 Litres'), ('15000 litres', '15,000 Litres'), ('35000 litres', '35,000 Litres'), ('45000 litres', '45,000 Litres')], max_length=20)),
                ('super_lpg', models.CharField(choices=[('super', 'Super'), ('lpg', 'LPG')], max_length=10)),
                ('quantity_of_load', models.PositiveIntegerField(default=0)),
                ('tank_capacity', models.CharField(default='10000 litres', max_length=20)),
                ('station_name', models.CharField(default='Main Station', max_length=100)),
                ('car_number', models.CharField(default='Unknown', max_length=20)),
                ('driver_name', models.CharField(default='Not Assigned', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilgas_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
