# Generated by Django 4.2.16 on 2024-10-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilgas', '0002_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lpg_price_per_kilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
