# Generated by Django 4.2.16 on 2024-10-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oilgas', '0003_fuelprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lpg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fuel_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oilgas.fuelprice')),
            ],
        ),
    ]
