# Generated by Django 4.2.16 on 2024-11-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilgas', '0004_fuelpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelprice',
            name='diesel_price_per_liter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fuelpricehistory',
            name='diesel_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
