# Generated by Django 4.2.16 on 2024-12-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_alter_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
