# Generated by Django 4.2.16 on 2025-01-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_remove_project_client_project_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
