# Generated by Django 4.2.16 on 2024-10-24 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_destination', models.CharField(default='Unknown', max_length=255)),
                ('to_destination', models.CharField(default='Unknown', max_length=255)),
                ('booking_date', models.DateField()),
                ('seat_number', models.PositiveIntegerField()),
                ('price_to_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_destination', models.CharField(choices=[('Accra', 'Accra'), ('Tema', 'Tema'), ('Madina', 'Madina'), ('Teshie', 'Teshie'), ('Nungua', 'Nungua'), ('Kumasi', 'Kumasi'), ('Obuasi', 'Obuasi'), ('Ejisu', 'Ejisu'), ('Mampong', 'Mampong'), ('Konongo', 'Konongo'), ('Sekondi-Takoradi', 'Sekondi-Takoradi'), ('Tarkwa', 'Tarkwa'), ('Axim', 'Axim'), ('Prestea', 'Prestea'), ('Sefwi-Wiawso', 'Sefwi-Wiawso'), ('Koforidua', 'Koforidua'), ('Akim Oda', 'Akim Oda'), ('Nkawkaw', 'Nkawkaw'), ('Suhum', 'Suhum'), ('Akwatia', 'Akwatia'), ('Ho', 'Ho'), ('Keta', 'Keta'), ('Hohoe', 'Hohoe'), ('Aflao', 'Aflao'), ('Denu', 'Denu'), ('Tamale', 'Tamale'), ('Yendi', 'Yendi'), ('Savelugu', 'Savelugu'), ('Bimbilla', 'Bimbilla'), ('Salaga', 'Salaga'), ('Cape Coast', 'Cape Coast'), ('Elmina', 'Elmina'), ('Winneba', 'Winneba'), ('Mankessim', 'Mankessim'), ('Saltpond', 'Saltpond'), ('Bolgatanga', 'Bolgatanga'), ('Navrongo', 'Navrongo'), ('Bawku', 'Bawku'), ('Zebilla', 'Zebilla'), ('Sandema', 'Sandema'), ('Wa', 'Wa'), ('Lawra', 'Lawra'), ('Tumu', 'Tumu'), ('Nandom', 'Nandom'), ('Jirapa', 'Jirapa'), ('Sunyani', 'Sunyani'), ('Berekum', 'Berekum'), ('Dormaa Ahenkro', 'Dormaa Ahenkro'), ('Wenchi', 'Wenchi'), ('Bechem', 'Bechem'), ('Techiman', 'Techiman'), ('Kintampo', 'Kintampo'), ('Nkoranza', 'Nkoranza'), ('Atebubu', 'Atebubu'), ('Yeji', 'Yeji'), ('Sefwi-Wiawso', 'Sefwi-Wiawso'), ('Bibiani', 'Bibiani'), ('Enchi', 'Enchi'), ('Juaboso', 'Juaboso'), ('Akontombra', 'Akontombra'), ('Dambai', 'Dambai'), ('Nkwanta', 'Nkwanta'), ('Kete Krachi', 'Kete Krachi'), ('Jasikan', 'Jasikan'), ('Chinderi', 'Chinderi'), ('Goaso', 'Goaso'), ('Bechem', 'Bechem'), ('Kenyasi', 'Kenyasi'), ('Duayaw Nkwanta', 'Duayaw Nkwanta'), ('Hwidiem', 'Hwidiem'), ('Damongo', 'Damongo'), ('Bole', 'Bole'), ('Salaga', 'Salaga'), ('Daboya', 'Daboya'), ('Sawla', 'Sawla'), ('Nalerigu', 'Nalerigu'), ('Walewale', 'Walewale'), ('Gambaga', 'Gambaga'), ('Bunkpurugu', 'Bunkpurugu'), ('Chereponi', 'Chereponi')], max_length=255)),
                ('to_destination', models.CharField(choices=[('Accra', 'Accra'), ('Tema', 'Tema'), ('Madina', 'Madina'), ('Teshie', 'Teshie'), ('Nungua', 'Nungua'), ('Kumasi', 'Kumasi'), ('Obuasi', 'Obuasi'), ('Ejisu', 'Ejisu'), ('Mampong', 'Mampong'), ('Konongo', 'Konongo'), ('Sekondi-Takoradi', 'Sekondi-Takoradi'), ('Tarkwa', 'Tarkwa'), ('Axim', 'Axim'), ('Prestea', 'Prestea'), ('Sefwi-Wiawso', 'Sefwi-Wiawso'), ('Koforidua', 'Koforidua'), ('Akim Oda', 'Akim Oda'), ('Nkawkaw', 'Nkawkaw'), ('Suhum', 'Suhum'), ('Akwatia', 'Akwatia'), ('Ho', 'Ho'), ('Keta', 'Keta'), ('Hohoe', 'Hohoe'), ('Aflao', 'Aflao'), ('Denu', 'Denu'), ('Tamale', 'Tamale'), ('Yendi', 'Yendi'), ('Savelugu', 'Savelugu'), ('Bimbilla', 'Bimbilla'), ('Salaga', 'Salaga'), ('Cape Coast', 'Cape Coast'), ('Elmina', 'Elmina'), ('Winneba', 'Winneba'), ('Mankessim', 'Mankessim'), ('Saltpond', 'Saltpond'), ('Bolgatanga', 'Bolgatanga'), ('Navrongo', 'Navrongo'), ('Bawku', 'Bawku'), ('Zebilla', 'Zebilla'), ('Sandema', 'Sandema'), ('Wa', 'Wa'), ('Lawra', 'Lawra'), ('Tumu', 'Tumu'), ('Nandom', 'Nandom'), ('Jirapa', 'Jirapa'), ('Sunyani', 'Sunyani'), ('Berekum', 'Berekum'), ('Dormaa Ahenkro', 'Dormaa Ahenkro'), ('Wenchi', 'Wenchi'), ('Bechem', 'Bechem'), ('Techiman', 'Techiman'), ('Kintampo', 'Kintampo'), ('Nkoranza', 'Nkoranza'), ('Atebubu', 'Atebubu'), ('Yeji', 'Yeji'), ('Sefwi-Wiawso', 'Sefwi-Wiawso'), ('Bibiani', 'Bibiani'), ('Enchi', 'Enchi'), ('Juaboso', 'Juaboso'), ('Akontombra', 'Akontombra'), ('Dambai', 'Dambai'), ('Nkwanta', 'Nkwanta'), ('Kete Krachi', 'Kete Krachi'), ('Jasikan', 'Jasikan'), ('Chinderi', 'Chinderi'), ('Goaso', 'Goaso'), ('Bechem', 'Bechem'), ('Kenyasi', 'Kenyasi'), ('Duayaw Nkwanta', 'Duayaw Nkwanta'), ('Hwidiem', 'Hwidiem'), ('Damongo', 'Damongo'), ('Bole', 'Bole'), ('Salaga', 'Salaga'), ('Daboya', 'Daboya'), ('Sawla', 'Sawla'), ('Nalerigu', 'Nalerigu'), ('Walewale', 'Walewale'), ('Gambaga', 'Gambaga'), ('Bunkpurugu', 'Bunkpurugu'), ('Chereponi', 'Chereponi')], max_length=255)),
                ('transport_type', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transport'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
