# Generated by Django 4.2.16 on 2024-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='from_destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transport',
            name='to_destination',
            field=models.CharField(max_length=255),
        ),
    ]
