# Generated by Django 4.2.16 on 2024-10-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_transport_from_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transport',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
