# Generated by Django 4.2.16 on 2024-10-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_rename_seat_number_booking_number_of_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_seat',
        ),
    ]
