# Generated by Django 4.2.16 on 2024-11-04 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_alter_product_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('offer_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('offer_end_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='special_offer_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='product.product')),
            ],
        ),
    ]
